name: gestion_certificats
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.3
  sticky_headers: ^0.3.0+2
  flutter_sticky_header: ^0.7.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  firebase_core: ^3.13.0
  flutter_form_builder: ^10.0.1
  cloud_firestore: ^5.6.7
  provider: ^6.1.5
  encrypt: ^5.0.3
  cryptography: ^2.7.0
  steel_crypt: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
