// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClBI91xuzHVzzaFQSm7ZntGP6cBAnKT2I',
    appId: '1:132052658864:web:a06bf90d053811226f2975',
    messagingSenderId: '132052658864',
    projectId: 'gestion-certificats',
    authDomain: 'gestion-certificats.firebaseapp.com',
    storageBucket: 'gestion-certificats.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA14L1-BL_IdN6V6HDI8Ol_Odbt7JoxPRg',
    appId: '1:132052658864:android:85a2e199b620a7106f2975',
    messagingSenderId: '132052658864',
    projectId: 'gestion-certificats',
    storageBucket: 'gestion-certificats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgAzbpaPlrfmaWk5YmmSFqbeLEePKMgJU',
    appId: '1:132052658864:ios:3c48395f2d9ab7726f2975',
    messagingSenderId: '132052658864',
    projectId: 'gestion-certificats',
    storageBucket: 'gestion-certificats.firebasestorage.app',
    iosBundleId: 'com.example.gestionCertificats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgAzbpaPlrfmaWk5YmmSFqbeLEePKMgJU',
    appId: '1:132052658864:ios:3c48395f2d9ab7726f2975',
    messagingSenderId: '132052658864',
    projectId: 'gestion-certificats',
    storageBucket: 'gestion-certificats.firebasestorage.app',
    iosBundleId: 'com.example.gestionCertificats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClBI91xuzHVzzaFQSm7ZntGP6cBAnKT2I',
    appId: '1:132052658864:web:9ff4602a3c9320836f2975',
    messagingSenderId: '132052658864',
    projectId: 'gestion-certificats',
    authDomain: 'gestion-certificats.firebaseapp.com',
    storageBucket: 'gestion-certificats.firebasestorage.app',
  );

}